version: '3'

networks:
  nextcloud_network:
    external: false

services:
  nextcloud:
    restart: always
    image: wsfy15/nextcloud15
    # build:
      # context: .
      # dockerfile: Dockerfile.15.0
    depends_on:
      - nextcloud-db           # If using MySQL
      # - solr                   # If using Nextant
      # - redis                  # If using Redis
    environment:
      - UID=sf
      - GID=sf
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
      - ADMIN_USER=admin            # Don't set to configure through browser
      - ADMIN_PASSWORD=admin        # Don't set to configure through browser
      - DOMAIN=localhost
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=supersecretpassword
      - DB_HOST=nextcloud-db
    ports:
      - 8888:8888
    volumes:
      - ./data:/data
      - ./config:/config # 一开始确保这个文件夹是空文件夹
      - ./apps:/apps2
      - ./themes:/nextcloud/themes
    networks:
      - nextcloud_network

  # If using MySQL
  nextcloud-db:
    restart: always
    image: mariadb:10
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecretpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=supersecretpassword
    networks:
      - nextcloud_network

      # If using Nextant
  # solr:
  #   image: solr:6-alpine
  #   container_name: solr
  #   volumes:
  #     - /docker/nextcloud/solr:/opt/solr/server/solr/mycores
  #   entrypoint:
  #     - docker-entrypoint.sh
  #     - solr-precreate
  #     - nextant
  #   networks:
  #     - nextcloud_network

  # If using Redis
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   volumes:
  #     - /docker/nextcloud/redis:/data
  #   networks:
  #     - nextcloud_network